### ISSUE TITLE
Failed assertion on failed compound condition just before run-out processing

### ISSUE THREAD

**Issue by yoavnir** [yoavnir/specs2016#204]
The following specification crashes on the input `yy`:
```
specs w1 a: if "a=='xx'" then @found@ 1 EOF @done@ 1
```
Error on Linux is:
```
Runtime error after reading 1 lines and using 1.

Exception: Failed assertion: !m_Conditions.empty()  (at: processing/ProcessingState.cc:552)
```
* It does not fail if the last iteration does succeed.
* It does not fail if there's no run-out part.
* It does not fail if we add the `ENDIF`.

**Comment by yoavnir** [comment]
Failure is in `ProcessingState::observeEndIf()`.  The code reaches that function twice (crashes on the second)

First time, while processing the lone record:
```
#0  0x0000000000474e1a in ProcessingState::observeEndIf() (this=0x7fffffffc9d0) at processing/ProcessingState.cc:550
#1  0x000000000043c95a in ConditionItem::apply(ProcessingState&, StringBuilder*) (this=0x7d6470, pState=..., pSB=0x7fffffffc9a0) at specitems/specItems.cc:849
#2  0x0000000000439041 in itemGroup::processDo(StringBuilder&, ProcessingState&, Reader*, classifyingTimer&, unsigned int&)
    (this=0x7fffffffc980, sb=..., pState=..., pRd=0x7d4770, tmr=..., rdrCounter=@0x7fffffffc64c: 1) at specitems/specItems.cc:419
#3  0x0000000000439889 in itemGroup::process(StringBuilder&, ProcessingState&, Reader&, classifyingTimer&) (this=0x7fffffffc980, sb=..., pState=..., rd=..., tmr=...) at specitems/specItems.cc:501
#4  0x000000000040ff59 in main(int, char**) (argc=10, argv=0x7fffffffcf90) at test/specs.cc:369
```

Second time, when the input ends:
```
#0  0x0000000000474e1a in ProcessingState::observeEndIf() (this=0x1004133fe) at processing/ProcessingState.cc:550
#1  0x000000000043c95a in ConditionItem::apply(ProcessingState&, StringBuilder*) (this=0x7d6470, pState=..., pSB=0x7fffffffc9a0) at specitems/specItems.cc:849
#2  0x0000000000439041 in itemGroup::processDo(StringBuilder&, ProcessingState&, Reader*, classifyingTimer&, unsigned int&)
    (this=0x7fffffffc980, sb=..., pState=..., pRd=0x7d4770, tmr=..., rdrCounter=@0x7fffffffc64c: 0) at specitems/specItems.cc:419
#3  0x0000000000439b90 in itemGroup::process(StringBuilder&, ProcessingState&, Reader&, classifyingTimer&) (this=0x7fffffffc980, sb=..., pState=..., rd=..., tmr=...) at specitems/specItems.cc:534
#4  0x000000000040ff59 in main(int, char**) (argc=10, argv=0x7fffffffcf90) at test/specs.cc:369
```
