### ISSUE TITLE
Crash when calculating a too-accurate float and an integer

### ISSUE THREAD

**Issue by yoavnir** [yoavnir/specs2016#241]
Seen on `Linux 4.18.0-513.el8.x86_64 #1 SMP Fri Aug 25 14:33:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

```
$ specs print "99.2189254761+1"
terminate called after throwing an instance of 'std::out_of_range'
  what():  stoi
Aborted (core dumped)
```
But
```
$ specs print "99.2189+1"
100.2189
```
And also 
```
$ specs print "99.2189254761+1.0"
100.2189254761
```

**Comment by yoavnir** [comment]
Backtrace:
```
(gdb) bt
#0  0x00007ffff62f9acf in raise () at /lib64/libc.so.6
#1  0x00007ffff62ccea5 in abort () at /lib64/libc.so.6
#2  0x00007ffff691809b in __gnu_cxx::__verbose_terminate_handler() [clone .cold.1] () at /lib64/libstdc++.so.6
#3  0x00007ffff691e54c in __cxxabiv1::__terminate(void (*)()) () at /lib64/libstdc++.so.6
#4  0x00007ffff691e5a7 in  () at /lib64/libstdc++.so.6
#5  0x00007ffff691e808 in  () at /lib64/libstdc++.so.6
#6  0x00007ffff691a045 in std::__throw_out_of_range(char const*) [clone .cold.4] () at /lib64/libstdc++.so.6
#7  0x0000000000413b66 in __gnu_cxx::__stoa<long, int, char, int>(long (*)(char const*, char**, int), char const*, char const*, unsigned long*, int) (__convf=0x7ffff62fe1d0 <strtoq>, __name=0x539fa3 "stoi", __str=0x7fffffffcce0 "2189254761+1", __idx=0x0) at /usr/include/c++/8/ext/string_conversions.h:86
#8  0x0000000000413004 in std::__cxx11::stoi(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long*, int) (__str="2189254761+1", __idx=0x0, __base=10) at /usr/include/c++/8/bits/basic_string.h:6415
#9  0x0000000000427ab8 in parseSingleToken(std::vector<Token, std::allocator<Token> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int) (pVec=0x7fffffffd210, arg="99.2189254761+1", argidx=1) at cli/tokens.cc:432
#10 0x000000000041a46e in parseTokensSplit(char const*) (arg=0x7fffffffda14 "99.2189254761+1") at cli/splitter.cc:110
#11 0x000000000042abbe in parseTokens(int, char**) (argc=1, argv=0x7fffffffd6b0) at cli/tokens.cc:537
#12 0x000000000040efd0 in main(int, char**) (argc=1, argv=0x7fffffffd6b0) at test/specs.cc:230
```

Looking in frame #9, we're in the try block in line 432 (this is version 0.9.2). 
* `fieldLength` = `2189254761+1` - so it kind of makes sense that `std::stoi` failed, but the `catch` statement catches `std::invalid_argument`, not `std::out_of_range`.

So ISTM that `std::stoi` is trying to parse `2189254761`, which exceeds `MAX_INT32`. `std::stoll` would have worked, but you can always stuff more digits and get it not to work.  Perhaps the catch should catch out of range and do something better...
