### ISSUE TITLE
Allow unquoted FieldSeparator and WordSeparator in file specifications

### ISSUE THREAD

**Issue by yoavnir** [yoavnir/specs2016#254]
The following spec file:
```
# Test WS and FS in files
FieldSeparator / Field 2
```

Causes this error:
```
Error reading specification tokens: Missing delimiter at end of input
```

This is because the slash (`/`) that is intended to be the field separator is treated as a delimiter.  When typing the same specification at the command line, there is no issue. Granted, you can't really use delimiters normally in the command line.  But still, the use of multi-character field and word separators is the exception, not the norm.  Let those cases use delimiters.

**Comment by yoavnir** [comment]
Where the problem is: `parseTokensSplit`

First, we read `FieldSeparator` into `sarg`, and call `parseSingleToken` to add `TokenListType__FIELDSEPARATOR` to the `ret` vector.

Then we call `isPossibleDelimiter` to check if `/` is a possible delimiter. The answer is yes.
```
(gdb) bt
#0  0x000000000041a0d7 in isPossibleDelimiter(char) (c=-1 '\377') at cli/splitter.cc:27
#1  0x000000000041a2f4 in parseTokensSplit(char const*) (arg=0x7ddf90 " FieldSeparator / Field 2 ") at cli/splitter.cc:62
#2  0x000000000041b14f in parseTokensFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (fileName="ttest") at cli/splitter.cc:206
#3  0x000000000040f20d in main(int, char**) (argc=0, argv=0x7fffffffd6d0) at test/specs.cc:228
```
So `st` is set to `SpSt__GettingChars`, the `delimiter` is set to `/`, and the program tries to read the rest of the line as a big string.

Eventually, we get to where `sarg` is `/ Field 2 ` and the stack looks like this:
```
(gdb) bt
#0  0x000000000041a6c1 in parseTokensSplit(char const*) (arg=0x7ddf90 " FieldSeparator / Field 2 ") at cli/splitter.cc:105
#1  0x000000000041b14f in parseTokensFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (fileName="ttest") at cli/splitter.cc:206
#2  0x000000000040f20d in main(int, char**) (argc=0, argv=0x7fffffffd6d0) at test/specs.cc:228
```
And finally, we get to line 114 where we find that we never found the delimiter.  

Guess the "right thing to do" is to search for the same (or matching) delimiter before treating the `/` as a delimiter.
