### ISSUE TITLE
SegFault with complex specification

### ISSUE THREAD

**Issue by yoavnir** [yoavnir/specs2016#40]
Crashed before reading any records:
```
if "words(6,7)=='structures created'" then
        /mh:/ 1
        print "#1" nw
        /count:/ nw
        print "#0" nw
        set "#1:=word(5)"
        set "#0:=0"
endif
if "word(6)=='CombId:'" then
        set "#0+=1"
endif
```

Running this with ALU debug, we seem to have premature evaluation:
```
specs -v -f xspc --debug-alu-comp --debug-alu-run
parseAluExpression: Parsing Expression: words(6,7)=='structures created'
Parsed Expression: ALU Vector at 0x7ffee378cb70 with 8 items:
       | FUNC(words)                             |
       | (                                       |
       | Number(6)                               |
       | COMMA                                   |
       | Number(7)                               |
       | )                                       |
       | BOP(==)                                 |
       | Literal(structures created)             |
       +-----------------------------------------+

Expression to Convert to RPN: ALU Vector at 0x7ffee378cb70 with 8 items:
       | FUNC(words)                             |
       | (                                       |
       | Number(6)                               |
       | COMMA                                   |
       | Number(7)                               |
       | )                                       |
       | BOP(==)                                 |
       | Literal(structures created)             |
       +-----------------------------------------+

RPN Expression: ALU Vector at 0x1e84a90 with 5 items:
       | Number(6)                               |
       | Number(7)                               |
       | FUNC(words)                             |
       | Literal(structures created)             |
       | BOP(==)                                 |
       +-----------------------------------------+

parseAluExpression: Parsing Expression: #1
Parsed Expression: ALU Vector at 0x7ffee378c9d0 with 1 items:
       | Counter(1)                              |
       +-----------------------------------------+

Expression to Convert to RPN: ALU Vector at 0x7ffee378c9d0 with 1 items:
       | Counter(1)                              |
       +-----------------------------------------+

RPN Expression: ALU Vector at 0x1e84508 with 1 items:
       | Counter(1)                              |
       +-----------------------------------------+

parseAluExpression: Parsing Expression: #0
Parsed Expression: ALU Vector at 0x7ffee378c9d0 with 1 items:
       | Counter(0)                              |
       +-----------------------------------------+

Expression to Convert to RPN: ALU Vector at 0x7ffee378c9d0 with 1 items:
       | Counter(0)                              |
       +-----------------------------------------+

RPN Expression: ALU Vector at 0x1e84618 with 1 items:
       | Counter(0)                              |
       +-----------------------------------------+

parseAluExpression: Parsing Expression: #1:=word(5)
Parsed Expression: ALU Vector at 0x7ffee378cb70 with 6 items:
       | Counter(1)                              |
       | ASS(:=)                                 |
       | FUNC(word)                              |
       | (                                       |
       | Number(5)                               |
       | )                                       |
       +-----------------------------------------+

Expression to Convert to RPN: ALU Vector at 0x7ffee378cb70 with 4 items:
       | FUNC(word)                              |
       | (                                       |
       | Number(5)                               |
       | )                                       |
       +-----------------------------------------+

RPN Expression: ALU Vector at 0x1e855e8 with 2 items:
       | Number(5)                               |
       | FUNC(word)                              |
       +-----------------------------------------+

parseAluExpression: Parsing Expression: #0:=0
Parsed Expression: ALU Vector at 0x7ffee378cb70 with 3 items:
       | Counter(0)                              |
       | ASS(:=)                                 |
       | Number(0)                               |
       +-----------------------------------------+

Expression to Convert to RPN: ALU Vector at 0x7ffee378cb70 with 1 items:
       | Number(0)                               |
       +-----------------------------------------+

RPN Expression: ALU Vector at 0x1e85928 with 1 items:
       | Number(0)                               |
       +-----------------------------------------+

parseAluExpression: Parsing Expression: word(6)=='CombId:'
Parsed Expression: ALU Vector at 0x7ffee378cb70 with 6 items:
       | FUNC(word)                              |
       | (                                       |
       | Number(6)                               |
       | )                                       |
       | BOP(==)                                 |
       | Literal(CombId:)                        |
       +-----------------------------------------+

Expression to Convert to RPN: ALU Vector at 0x7ffee378cb70 with 6 items:
       | FUNC(word)                              |
       | (                                       |
       | Number(6)                               |
       | )                                       |
       | BOP(==)                                 |
       | Literal(CombId:)                        |
       +-----------------------------------------+

RPN Expression: ALU Vector at 0x1e85a20 with 4 items:
       | Number(6)                               |
       | FUNC(word)                              |
       | Literal(CombId:)                        |
       | BOP(==)                                 |
       +-----------------------------------------+

parseAluExpression: Parsing Expression: #0+=1
Parsed Expression: ALU Vector at 0x7ffee378cb70 with 3 items:
       | Counter(0)                              |
       | ASS(+=)                                 |
       | Number(1)                               |
       +-----------------------------------------+

Expression to Convert to RPN: ALU Vector at 0x7ffee378cb70 with 1 items:
       | Number(1)                               |
       +-----------------------------------------+

RPN Expression: ALU Vector at 0x1e858d8 with 1 items:
       | Number(1)                               |
       +-----------------------------------------+

After parsing, index = 17/17
itemGroup has 13 items:
1. IF(words(6,7)=='structures created')
2. THEN
3. {Source=/mh:/;Dest=1}
4. {Source=Expression:#1;Dest=NextWord}
5. {Source=/count:/;Dest=NextWord}
6. {Source=Expression:#0;Dest=NextWord}
7. #1:=word(5)
8. #0:=0
9. ENDIF
10. IF(word(6)=='CombId:')
11. THEN
12. #0+=1
13. ENDIF

============= evaluateExpression ==============
Expression Progress: ALU Vector at 0x1e84a90 with 5 items:
   ==> | Number(6)                               |
       | Number(7)                               |
       | FUNC(words)                             |
       | Literal(structures created)             |
       | BOP(==)                                 |
       +-----------------------------------------+

Execution Stack: ALU Stack at 0x7ffee378ca30 with 0 items:



Expression Progress: ALU Vector at 0x1e84a90 with 5 items:
       | Number(6)                               |
   ==> | Number(7)                               |
       | FUNC(words)                             |
       | Literal(structures created)             |
       | BOP(==)                                 |
       +-----------------------------------------+

Execution Stack: ALU Stack at 0x7ffee378ca30 with 1 items:
   > 6



Expression Progress: ALU Vector at 0x1e84a90 with 5 items:
       | Number(6)                               |
       | Number(7)                               |
   ==> | FUNC(words)                             |
       | Literal(structures created)             |
       | BOP(==)                                 |
       +-----------------------------------------+

Execution Stack: ALU Stack at 0x7ffee378ca30 with 2 items:
   > 7
   > 6



Segmentation fault (core dumped)
```

Stack:
```
(gdb) bt
#0  0x000000000042de54 in ProcessingState::getFromTo(int, int) (this=0x7fffffffdd40, from=0, to=0) at processing/ProcessingState.cc:183
#1  0x000000000044902a in AluFunc_range(ALUInt, ALUInt) (start=0, end=0) at utils/aluFunctions.cc:164
#2  0x000000000044930e in AluFunc_words(ALUValue*, ALUValue*) (pStart=0x672b70, pEnd=0x672a60) at utils/aluFunctions.cc:203
#3  0x000000000043e85a in AluFunction::compute(ALUValue*, ALUValue*) (this=0x6718a0, op1=0x672b70, op2=0x672a60) at utils/alu.cc:881
#4  0x0000000000442500 in evaluateExpression(std::vector<AluUnit*, std::allocator<AluUnit*> >&, ALUCounters*) (expr=..., pctrs=0x66a2e0 <g_counters>) at utils/alu.cc:1443
#5  0x0000000000419af5 in ConditionItem::apply(ProcessingState&, StringBuilder*) (this=0x671a80, pState=..., pSB=0x7fffffffdec0) at specitems/specItems.cc:421
#6  0x0000000000418131 in itemGroup::processDo(StringBuilder&, ProcessingState&, Reader*, Writer*) (this=0x7fffffffdc00, sb=..., pState=..., pRd=0x7fffffffdc20, pWr=0x0) at specitems/specItems.cc:183
#7  0x0000000000405123 in main(int, char**) (argc=0, argv=0x7fffffffe110) at test/specs.cc:144
```
Moving the words(6,7) outside makes this not crash

**Comment by yoavnir** [comment]
```
commit c25c0442efe6a05b1baebc3cc3c1fd9618c51814
Author: synp71 <yoav.nir@gmail.com>
Date:   Tue Jan 8 22:11:35 2019 +0200

    Issue #40: Detect when expressions require input lines
    
    Items other than dataitems did not return the correct value form the readsLines() method.
```
